image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '9'
    - nodejs_version: '10'
    - nodejs_version: '11'

platform:
    - x86
    - x64

cache:
    - node_modules                        # local npm modules
    - '%APPDATA%\npm-cache'               # npm cache

install:
    - ps: Install-Product node $env:nodejs_version
    - set CI=true
    - npm -g install npm@latest
    - npm -g install eslint
    - set PATH=%APPDATA%\npm;%PATH%
    - npm install

matrix:
    fast_finish: true

build: off

shallow_clone: true

test_script:
    - |
      docker pull --platform linux grokzen/redis-cluster:4.0.8
      docker run -d -p 7000:7000 -p 7001:7001 -p 7002:7002 -p 7003:7003 -p 7004:7004 -p 7005:7005 -e "IP=0.0.0.0" --name redis-cluster grokzen/redis-cluster:4.0.8
      export REDIS_CLUSTER_HOSTS='localhost:7000 localhost:7001 localhost:7002 localhost:7003 localhost:7004 localhost:7005'

    - node --version
    - npm --version
    - npm test
